### ISSUE TITLE
Appears to be a problem with the pubspec.yaml in the component

### ISSUE THREAD

**Issue by rayk** [bwu-dart/bwu_polymer_routing#6]
Loading di transformers...
Error on line 23, column 3 of ../../.pub-cache/hosted/pub.dartlang.org/bwu_polymer_routing-0.1.1+1/pubspec.yaml: Error loading transformer: Invalid arguments(s): sdkDirectory must be provided.
- di
  ^^^

appears be to related to issue number #4

**Comment by zoechi** [comment]
#4 should be fixed since a while (forgot to close). 
This is related to https://github.com/angular/angular.dart/issues/1270
This should also be fixed with 0.2.3+2 of the `code_transformer` package.
What version of that package do you use?

**Comment by GeReinhart** [comment]
I've the same issue : 

--- 10:44:05 PM Running pub upgrade on /media/gex/Data1/Dev/app-connecting-dartisans ... ---
Resolving dependencies...
 (...)
  bwu_polymer_routing 0.1.1+1 from git git://github.com/bwu-dart/bwu_polymer_routing.git
  code_transformers 0.2.3+2
  polymer 0.15.5
  route_hierarchical 0.6.1
  di 3.3.3
  (...)
No dependencies changed.
Precompiling dependencies...
Loading source assets...
Loading di/module_transformer, initialize/build/loader_replacer, polymer/src/build/mirrors_remover, code_transformers/src/delete_file, observe, smoke/src/default_transformer and initialize transformers...
Loading polymer and di transformers...
Error on line 23, column 3 of /home/gex/.pub-cache/git/bwu_polymer_routing-e6594eeb0c9e136d735165b3e49bc590982606b1/pubspec.yaml: Error loading transformer: Invalid arguments(s): sdkDirectory must be provided.
- di
  ^^^

**Comment by zoechi** [comment]
`bwu_polymer_routing` doesn't have a direct dependency on `code_transformers`.
The `di` dependency specifies `code_transformers: '>=0.2.3 <0.3.0'` though, which allows a version `< 0.2.3+2`.
Until this is updated it should be sufficient to add a `code_transformers` dependency in your own `pubspec.yaml` like `code_transformers: '>=0.2.3+2 <0.3.0`. to solve your issue.

**Comment by GeReinhart** [comment]
It's what I've done, see the dependencies retrieved in the previous comment. But I still have the issue...

**Comment by zoechi** [comment]
Can you please post your `pubspec.yaml`?

**Comment by GeReinhart** [comment]
My CI is now green : https://drone.io/github.com/GeReinhart/app-connecting-dartisans/32 with https://github.com/GeReinhart/app-connecting-dartisans/blob/210574e3c33e1cba94b1981a35c09d83a2441909/pubspec.yaml

On my machine, on Ubuntu, the intallation of dartsdk is done through https://launchpad.net/~hachre/+archive/ubuntu/dart. The sdk is deployed under /opt/google/dartsdk. And I think that it's the root of the problem (for me). 

From my point of view, you can close the issue. Thanks

**Comment by zoechi** [comment]
Great,  thanks for the feedback!
